import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '../components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='pl' data-theme='dracula'>
            <body className={inter.className}>
                <Header />
                <main className='mt-8 flex flex-col items-center'>
                    {children}
                </main>
            </body>
        </html>
    );
}
