import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '../components/Header';
import SessionProvider from './SessionProvider';
import Footer from '@/components/Footer';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='pl' data-theme='dracula'>
            <body className={`${inter.className} flex min-h-screen flex-col`}>
                <SessionProvider>
                    <Header />
                    <main className='my-9 flex flex-1 flex-col items-center gap-9'>
                        {children}
                    </main>
                    <Footer />
                </SessionProvider>
            </body>
        </html>
    );
}
